### PR TITLE
koin upgrade to 3.2.2 

### PR DESCRIPTION
**Pull request by mrclrchtr**
With the current version, I get the following error message when I upgrade Gradle from 7.4.2 to 7.5.1 and then want to use the keycloak migration:

```
Caused by: java.lang.NoSuchMethodError: 'double kotlin.time.Duration.toDouble-impl(long, java.util.concurrent.TimeUnit)'
        at org.koin.core.time.MeasureKt.measureDuration(Measure.kt:32)
        at org.koin.core.KoinApplication.modules(KoinApplication.kt:59)
        at org.koin.core.KoinApplication.modules(KoinApplication.kt:42)
        at de.klg71.keycloakmigration.MainKt$migrate$1$1.invoke(Main.kt:68)
        at de.klg71.keycloakmigration.MainKt$migrate$1$1.invoke(Main.kt:66)
        at org.koin.core.context.GlobalContext.startKoin(GlobalContext.kt:64)
        at org.koin.core.context.DefaultContextExtKt.startKoin(DefaultContextExt.kt:31)
        at de.klg71.keycloakmigration.MainKt.migrate(Main.kt:66)
        at de.klg71.keycloakmigrationplugin.KeycloakMigrationTask.migrate(KeycloakMigrationTask.kt:55)
....
```

I checked out the plugin locally, pulled up the version and then tried it with that. The error then does not occur.

### CODE REVIEW

**Comment by klg71** [comment]
Hey mrclrchtr,
Thanks for your Merge Request :) It looks all fine. I will shortly release another version but I'm waiting for another MR. This shouldn't take longer than this week for the next release :)
Greetings From Germany :)

**Review by klg71 — APPROVED** [review]

**Comment by klg71** [comment]
Released with 0.2.39
